### ISSUE TITLE
s2s audit

### ISSUE THREAD

**Issue by xiaoch05** [helix-bridge/contracts#12]
- [x] s2s token bridge @hujw77 @HackFisher 
- https://github.com/helix-bridge/contracts/blob/master/helix-contract/contracts/mapping-token/v2/erc20-mapping-protocol/Erc20Sub2SubBacking.sol
- https://github.com/helix-bridge/contracts/blob/master/helix-contract/contracts/mapping-token/v2/erc20-mapping-protocol/Erc20Sub2SubMappingTokenFactory.sol
- [https://github.com/helix-bridge/contracts/blob/master/helix-contract/contracts/mapping-token/v2/message-endpoints/DarwiniaSub2SubMessageEndpoint.sol](https://github.com/4de67ebf656242639b762e4f42ff9f1b)
- [x] s2s SDK @AsceticBear @hujw77 
- https://github.com/darwinia-network/darwinia-messages-sol/tree/master/contracts/periphery/contracts/s2s

**Comment by hujw77** [comment]
https://github.com/darwinia-network/darwinia-messages-sol/issues/238

**Comment by hujw77** [comment]
https://github.com/darwinia-network/darwinia-messages-sol/issues/239

**Comment by hujw77** [comment]
https://github.com/helix-bridge/contracts/blob/d3ef6a9d87e8f7efde0c540c2b4688d40141106b/helix-contract/contracts/mapping-token/v2/message-endpoints/DarwiniaSub2SubMessageEndpoint.sol#L51

Dead code.

**Comment by hujw77** [comment]
https://github.com/helix-bridge/contracts/blob/d3ef6a9d87e8f7efde0c540c2b4688d40141106b/helix-contract/contracts/mapping-token/v2/message-endpoints/DarwiniaSub2SubMessageEndpoint.sol#L9
https://github.com/helix-bridge/contracts/blob/d3ef6a9d87e8f7efde0c540c2b4688d40141106b/helix-contract/contracts/mapping-token/v2/Backing.sol#L26

Add helix dao to be a admin role.
