### ISSUE TITLE
Deprecated issues from darwinia-bridges-sol

### ISSUE THREAD

**Issue by hackfisher** [helix-bridge/contracts#2]
https://github.com/darwinia-network/darwinia-bridges-sol/issues/28

https://github.com/darwinia-network/darwinia-bridges-sol/issues/86

https://github.com/darwinia-network/darwinia-bridges-sol/issues/97

https://github.com/darwinia-network/darwinia-bridges-sol/issues/111

https://github.com/darwinia-network/darwinia-bridges-sol/issues/98

**Comment by xiaoch05** [comment]
all issues listed here are fixed or deprecated.
