### ISSUE TITLE
xRING ([Darwinia=>)) on Crab need to be migrated to new xRING token ([Darwinia Smart=>))

### ISSUE THREAD

**Issue by hackfisher** [helix-bridge/contracts#9]
Related #7 

Some xRING are located in Ethereum pallet account id (root_transact)? need to take of it when doing migration.

**Comment by HackFisher** [comment]
1. Enable Darwinia Smart <> Crab Smart, and register new xWRING (decimal 18).
2. Disable old Darwinia <> Crab Smart, xRING(decimal 9) need to be migrated.
3. Use the backing RING asset in backing pallet on Darwinia side, and cross-chain transfer them through Darwinia Smart <> Crab Smart(Might need assistance of migration). Same amount of xWRING will be created for old xRING migration.
4. Deploy a new migration contract for xRING holders to burndrop/exchange xRING to xWRING in 1:1 ratio.  Old xRING will be be burned, same amount of xWRING will be withdrawn to same holder.

**Comment by HackFisher** [comment]
Old xRING token holder list: https://crab.subscan.io/erc20_token/0x7399ea6c9d35124d893b8d9808930e9d3f211501?tab=holder


This holder is the pallet account of ethereum and sender of `root_transact`, so kind of special and need to take care of during migration(governance proposal).

https://crab.subscan.io/account/0x6D6F646C6461722f64766D700000000000000000?tab=erc20_transfer
